version: '3.8'

services:
  backend:
    build: ./flask-backend
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    build: ./vue-frontend
    ports:
      - "3000:80"
    environment:
      - VITE_API_BASE_URL=http://backend:5000
    networks:
      - app-network

networks:
  app-network: